name: CI

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3.0.2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11

      - name: Run SBT tasks
        run: >
          sbt
          scalafmtCheckAll
          scalafmtSbtCheck
          test
          
